[tool.briefcase]
project_name = "commissionApp"
bundle = "com.developer"
version = "0.0.1"
url = "https://developer.com/commissionApp"
license = "BSD license"
author = 'developer'
author_email = "developer@developer.com"

[tool.briefcase.app.commissionApp]
formal_name = "commissionApp"
description = "My first application"
icon = "src/commissionApp/resources/commissionApp"
sources = ['src/commissionApp']
requires = [
]


[tool.briefcase.app.commissionApp.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.commissionApp.linux]
requires = [
    'toga-gtk>=0.3.0.dev34',
]

[tool.briefcase.app.commissionApp.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.commissionApp.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.commissionApp.windows]
requires = [
    'toga-winforms>=0.3.0.dev34',
]

# Mobile deployments
[tool.briefcase.app.commissionApp.iOS]
requires = [
    'toga-iOS>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.commissionApp.android]
requires = [
    'toga-android>=0.3.0.dev34'
]
